<h1>FindAllVideos</h1>
<?php $i = 1 ?>
<?php foreach ($this->paginator as $video): ?>
  <div class="item">
    <h2><?php echo $i++ . '. ' . $video->getName() ?></h2>
    <div class="item_body">
      <dl>
      <?php foreach ($video as $property => $value): ?>
        <dt><?php echo $property ?></dt>
        <dd><?php echo $value ?></dd>
      <?php endforeach ?>
      </dl>
    </div>
  </div>
<?php endforeach ?>
<?php echo $this->paginator ?>